# Generated by Django 4.2.4 on 2023-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=80)),
                ('telefono', models.IntegerField(max_length=15)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('email', models.EmailField(max_length=80)),
                ('estado', models.CharField(max_length=15)),
                ('observacion', models.CharField(max_length=255)),
            ],
        ),
    ]
